### ISSUE TITLE
Extending COVA to extract path constraints

### ISSUE THREAD

**Issue by imranur-rahman** [secure-software-engineering/COVA#16]
Hi, I have read the paper and tried your tool. However, I want to extract Interprocedural path constraints from an Android apk. But I am not properly sure how to modify COVA to do that (since COVA is created for Taint analysis). Can you please tell me if you have any idea how to do that or any idea how to move forward in that direction?

The path constraints don't have to be starting from dummyMainMethod. It can simply start from any method (i.e., a callback function of Android framework) and end in its' return statements. But in my case, I need the Interprocedural path constraints starting from that function. Any help is highly appreciated.

Thanks in advance!

**Comment by linghuiluo** [comment]
Hi, you can use it as a standalone tool without FlowDroid as section 3 Running The Command-Line Tool (2) Standalone in the readme https://github.com/secure-software-engineering/COVA says.

**Comment by imranur-rahman** [comment]
Thanks for the reply. I tried to do what you said. Unfortunately, I can't run COVA as a standalone tool. It gets stuck after initializing Soot.  However, previously I ported the necessary parts of COVA to another project to try the standalone part and modified "Configuration_API" file to contain no API. To be clear, I do not have any specific configuration API and no specific source and sink (I don't want to do Taint analysis, I want to generate simple path constraints for each statement). When I run that with no configuration API, a constraint map is computed but all statements of the map contain constraint "true".

Any help?

**Comment by linghuiluo** [comment]
COVA only tracks constraints that are relevant to the APIs configured. If you run it without any API, surely it wont compute any path constraints.

**Comment by linghuiluo** [comment]
@irshimul Is this issue now resolved?

**Comment by imranur-rahman** [comment]
Yes, thanks. I am closing the issue.
