### ISSUE TITLE
Unable to find cova.jar

### ISSUE THREAD

**Issue by geekySR** [secure-software-engineering/COVA#21]
I would like to use COVA as a command line tool. However, I couldn't find cova.jar in my target folder. There are other jars present (See my target directory for instance): 
I tried mvn install in the root directory as well.

d-----        28-07-2022  08.58 PM                classes
d-----        28-07-2022  08.58 PM                maven-archiver
d-----        28-07-2022  08.58 PM                maven-status
d-----        02-08-2022  06.02 PM                surefire-reports
d-----        28-07-2022  08.58 PM                test-classes
-a----        02-08-2022  06.03 PM       36207482 cova-0.0.1-SNAPSHOT-shaded.jar
-a----        02-08-2022  06.03 PM       36207482 cova-0.0.1-SNAPSHOT.jar
-a----        02-08-2022  06.03 PM       36207482 original-cova-0.0.1-SNAPSHOT.jar

**Comment by linghuiluo** [comment]
just take the shaded one. it is the cova.jar

**Comment by geekySR** [comment]
Sure, Thanks for the reply!
